# Generated by Django 3.2.3 on 2021-11-02 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='poll',
            old_name='option1',
            new_name='option_one',
        ),
        migrations.RenameField(
            model_name='poll',
            old_name='option1_count',
            new_name='option_one_count',
        ),
        migrations.RenameField(
            model_name='poll',
            old_name='option2',
            new_name='option_three',
        ),
        migrations.RenameField(
            model_name='poll',
            old_name='option2_count',
            new_name='option_three_count',
        ),
        migrations.RenameField(
            model_name='poll',
            old_name='option3',
            new_name='option_two',
        ),
        migrations.RenameField(
            model_name='poll',
            old_name='option3_count',
            new_name='option_two_count',
        ),
    ]
